version: "2.1"
services:
  atana:
    image: axini/atana:latest
    ports:
      - 8090:8080
    environment:
      - PROFILE=docker
      - spring.datasource.url=jdbc:mysql://db:3306/atana?useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=developer
    links:
      - db:db
  db:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_DATABASE=atana
      - MYSQL_USER=atana
      - MYSQL_PASSWORD=developer
      - MYSQL_RANDOM_ROOT_PASSWORD=yes